micronaut:
  application:
    name: employee-service
  server:
    port: 8090

consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"

tracing:
  zipkin:
    http:
      url: http://localhost:9411
    enabled: true
    sampler:
      probability: 1

dataSources:
  default:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: 'postgres'
    password: ''
    driver-class-name: org.postgresql.Driver

flyway:
  datasources:
      default:
         locations: classpath:databasemigrations
         baselineOnMigrate: true
         baselineVersion: 1

endpoints:
  flyway:
    enabled: true
    sensitive: false
